begin make map-filter.js
htmlacademy-javascript/1577653-keksobooking-22 pull request #11
Opened 2021-03-18 10:04 UTC by olga-aheichyk

2021-03-18 11:43 UTC, ademaro requested changes
жду поправок тогда

2021-03-18 18:35 UTC, olga-aheichyk commented
Антон, я сделала, что работает перерисовка по изменению типа жилья, оно работает, но по поводу самой реализации я сомневаюсь, что ты одобришь

2021-03-19 11:31 UTC, ademaro commented on js/pins.js
> +  pins.slice(0, PINS_ON_MAP_COUNT)
обрезать давай в фильтре, рендер должен показывать всё, что пришло

2021-03-19 11:36 UTC, ademaro commented on js/pins.js
> +      setHousingTypeChange(pins, map, adPin);
для каждого пина ты навешиваешь housingType.addEventListener('change'... ? Немного не с той стороны пошли. Надо:
1. получаем пины
2. сохраняем
3. фильтруем (в первом случае будет только один "фильтр" — обрезка до 10 штук)
4. показываем
5. вешаем обработчик на смену фильтров
6. при смене фильтра — опять фильтруем что изначально сохранили, показываем что отфильтровали

2021-03-19 11:37 UTC, ademaro commented on js/map-filter.js
> +      for (let i=0; i < pins.length; i++) {
а чего не forEach()

2021-03-19 11:37 UTC, ademaro commented on js/map-filter.js
> +    if (evt.target.value !== 'any') {
сам фильтр по типу жилья — норм.

2021-03-19 11:37 UTC, ademaro requested changes
Жду поправок)

2021-03-21 13:08 UTC, ademaro commented on js/pins.js
> +export { renderPins, adPins };
addPins

2021-03-21 13:09 UTC, ademaro approved these changes
Отлично, летим в остальную фильтрацию

2021-03-21 13:09 UTC, merged