write 2 functions at main.js
htmlacademy-javascript/1577653-keksobooking-22 pull request #2
Opened 2021-02-01 11:54 UTC by olga-aheichyk

2021-02-01 13:31 UTC, ademaro commented on js/main.js
> +  if (Math.sign(firstNumber) >= 0 && Math.sign(secondNumber) >= 0) {
Зачем тебе тут Math.sign() ?)

2021-02-01 13:33 UTC, ademaro commented on js/main.js
> +    let randomNumber = Math.random() * (max - min) + min;
Обрати внимание, что строчки с кодом повторяются. Давай подумаем, как можно вынести повторяющийся код)

2021-02-01 13:34 UTC, ademaro commented on js/main.js
> +      let min = secondNumber;
Может, сразу назвать параметры min/max? И лишние переменные не нужны будут...

2021-02-01 13:34 UTC, ademaro requested changes
Давай чутка перепишем, что бы вообще супер было) В целом — очень хорошо, ты молодец! Понимание функций у тебя уже есть!

2021-02-02 08:03 UTC, olga-aheichyk commented
Антон, переписала функции, оказывается, можно было не усложнять этим Math.sign и переопределением атрибутов. 
Но как переиспользовать код не придумалось, только если написать одну функцию для генерации случайного числа, а потом в константах или округлять до целого числа (чтобы получить результат первой функции), или применять toFixed, чтобы получить результат второй. Но тогда это уже не две функции.

2021-02-02 12:05 UTC, ademaro approved these changes
Отлично! Смотри как стало более читаемо и более лаконично! Молодец!! ПР закрываю.

2021-02-02 12:05 UTC, merged