begin map-customizatiom
htmlacademy-javascript/1577653-keksobooking-22 pull request #7
Opened 2021-02-22 16:35 UTC by olga-aheichyk

2021-02-23 17:26 UTC, olga-aheichyk commented
Антон, привет! Задание вроде выполнила. Только линтер ругается на Leaflet, что с этим можно сделать?

2021-02-24 12:03 UTC, ademaro commented on index.html
> +    <!-- integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
коммент можем удалять)

2021-02-24 12:05 UTC, ademaro commented on js/main.js
> +  popupElement.querySelector('.popup__text--address').textContent = `Координаты: ${object.location.x}, ${object.location.y}`;
почему это не сразу в createCardLayout? Нам не надо так разносить по кускам отрисовку данных на разные файлы/функции, давай соберём в одном месте сразу.

2021-02-24 12:06 UTC, ademaro commented on js/main.js
> +for (let i = 0; i < mockObjects.length; i++) {
тут давай for заменим перебирающим методом массива...

2021-02-24 12:07 UTC, ademaro commented on js/main.js
> +    iconSize: [25, 41],
25, 41 — константы

2021-02-24 12:08 UTC, ademaro commented on js/map.js
> +const TOKYO_CENTER = {
константные значения — в начало модуля
[Б10](https://up.htmlacademy.ru/javascript/22/criteries#b10)

2021-02-24 12:09 UTC, ademaro commented on js/map.js
> +    inputAddress.value = `Координаты: ${TOKYO_CENTER.x}, ${TOKYO_CENTER.y}`;
слово `Координаты: ` — лишнее, на сколько я помню...

2021-02-24 12:10 UTC, ademaro commented on js/map.js
> +  iconSize: [50, 82],
константы

2021-02-24 12:11 UTC, ademaro commented on js/map.js
> +  inputAddress.value = `Координаты: ${evt.target.getLatLng().lat.toFixed(5)}, ${evt.target.getLatLng().lng.toFixed(5)}`;
5 — так же магическое значение, числовые литералы — в константы 
[Д19](https://up.htmlacademy.ru/javascript/22/criteries#d19)

2021-02-24 12:13 UTC, ademaro commented on js/main.js
> +for (let i = 0; i < mockObjects.length; i++) {
вообще предлагаю сделать ещё модуль pins.js, там сделать примерно такую ф-цию: `insertPinsToMap(map, pins);`, тут ей передать только пины и карту, остальное — всё там)

2021-02-24 12:14 UTC, ademaro requested changes
Предлагаю сразу всё поправить и двинем дальше. ПР пока оставляю открытым. По коду всё отлично. Небольшие архитектурные моменты правим и закрою ПР.

2021-02-26 09:02 UTC, ademaro commented on js/create-card-layout.js
> +    articleFeatures.style.display = 'none';
можно просто `articleFeatures.remove()`, думаю...

2021-02-26 09:11 UTC, ademaro commented on js/map.js
> +const TOKYO_CENTER = {
Это тогда уже перечисление, надо оформить с соответствии с критериями

2021-02-26 09:11 UTC, ademaro commented on js/pins.js
> +const mockObjects = makeCards(CARDS_COUNT);
Это в main.js

2021-02-26 09:18 UTC, ademaro commented on js/pins.js
> +mockObjects.forEach((item) => {
Для рендера пинов давай сделаем отдельную ф-цию, её экспортируем, запускать так же в main.js будем

2021-02-26 09:20 UTC, ademaro commented on js/util.js
> +  for (let i = 0; i < interactiveElements.length; i++) {
for и тут меняем на forEach

2021-02-26 09:22 UTC, ademaro approved these changes
Пока закрываю, двигаем в следующую часть. Предлагаю на днях созвониться нам всем вместе, обсудить детали дополнительно)

2021-02-26 09:22 UTC, merged